name: 'my first container action'
description: 'A cloud guru'
author: 'Michael Brown'
inputs:
    myInput:
        description: 'greeting to use'
        required: true
        default: 'Awesome Guru'
runs:
    using: 'docker'
    image: 'Dockerfile'
    
